language: python

python:
- '3.4'
- '3.5'
- '3.6'

install:
- pip install .
- pip install -r requirements.txt

script: travis_retry coverage run -m pytest

deploy:
  provider: pypi
  user: josephmancuso
  password:
    secure: WQo8L+H+PxetWuNIVSjKkSP/tgJLA+mNb4MRarmnnsc1sbUK23eF4syIAjvg90AnKo0BbCktmGt37HVuu5UHwfR13g5X1Bp3JaTr6RciR+hig8Fa0n2Vlwdy5YI7UNRX5r3cyVeryZRTgfMx/ALIwAz6/vJHz4AHezVcT0oO5yJ7mhlCx45dS5tTsZnU0vvNzGSMhuKq8lwPj632S6DUa8J5GwIubdj6PigSDhHTRZyMOxoyBq+uwWH0/hmKHcpXHG5n5iF94wZ8bwmmHHl5cXdhwbMBDu4+82cYoJSDtLA4IcRbtdUpYdX+vrQf1cte7lkUbKr6WUBaeAAtO2IFow+Fi/RROVxO3Smygi+XkIXgoSVNlRFaT1DnqM9zTEeeeb0hGrmdKtqCLTcHEKayoQJFpp6Q2w4iHwjk+xJuj0Kj8jJenTURUxoYwW8KYGvOJoFDRmXjntI6Mh2Gp3sZ3Kwc/XVyCzNmFfvlOBWgWAooqvzN5zxlCv7lGBcPtoNazAwGKF4znVULx0WzkckqImNYohEwxtbLvTouwTpLZPaHF+GwJMSPcoOilAsju0+3EBsPWGUpXuV4Nae09nkbemsyRqYM9lcLaNlKBME/Jqk7cdWa3OLAsVrcjfToPJLJZx5FwpzPEO/6Omq83zaCYW3Z06sf+cnAhrdOaaWWKTQ=
  on:
    tags: true
    python: 3.6

after_success:
  coveralls